"""initial-3

Revision ID: 3d0716616da4
Revises: a81d2fe63f88
Create Date: 2026-04-01 14:51:29.714704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3d0716616da4"
down_revision: Union[str, None] = "a81d2fe63f88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "type",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "type")
    # ### end Alembic commands ###
