"""initial-2

Revision ID: 55bc15bb2fff
Revises: 2ade0e8bc98a
Create Date: 2026-04-14 15:10:33.165369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "55bc15bb2fff"
down_revision: Union[str, None] = "2ade0e8bc98a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topics", sa.Column("background", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topics", "background")
    # ### end Alembic commands ###
