"""initial-8

Revision ID: 7a2d1dbca2bd
Revises: cb0f353604ff
Create Date: 2026-04-07 16:32:45.895304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7a2d1dbca2bd"
down_revision: Union[str, None] = "cb0f353604ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pinned_messages",
        sa.Column("executor_id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["executor_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pinned_messages_conversation_id"),
        "pinned_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pinned_messages_created_at"),
        "pinned_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pinned_messages_deleted"),
        "pinned_messages",
        ["deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pinned_messages_executor_id"),
        "pinned_messages",
        ["executor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pinned_messages_id"), "pinned_messages", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pinned_messages_message_id"),
        "pinned_messages",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pinned_messages_message_id"), table_name="pinned_messages"
    )
    op.drop_index(op.f("ix_pinned_messages_id"), table_name="pinned_messages")
    op.drop_index(
        op.f("ix_pinned_messages_executor_id"), table_name="pinned_messages"
    )
    op.drop_index(
        op.f("ix_pinned_messages_deleted"), table_name="pinned_messages"
    )
    op.drop_index(
        op.f("ix_pinned_messages_created_at"), table_name="pinned_messages"
    )
    op.drop_index(
        op.f("ix_pinned_messages_conversation_id"),
        table_name="pinned_messages",
    )
    op.drop_table("pinned_messages")
    # ### end Alembic commands ###
