"""initial-7

Revision ID: cb0f353604ff
Revises: ebd9d64eac4b
Create Date: 2026-04-07 14:17:25.309620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cb0f353604ff"
down_revision: Union[str, None] = "ebd9d64eac4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_conversations_created_at"),
        "conversations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_files_created_at"), "files", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_members_created_at"), "members", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_messages_created_at"),
        "messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_type"), "messages", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_topics_created_at"), "topics", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_users_created_at"), "users", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_topics_created_at"), table_name="topics")
    op.drop_index(op.f("ix_messages_type"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_members_created_at"), table_name="members")
    op.drop_index(op.f("ix_files_created_at"), table_name="files")
    op.drop_index(
        op.f("ix_conversations_created_at"), table_name="conversations"
    )
    # ### end Alembic commands ###
