"""initial-6

Revision ID: ebd9d64eac4b
Revises: 006970a1bf0b
Create Date: 2026-04-06 17:37:47.531726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ebd9d64eac4b"
down_revision: Union[str, None] = "006970a1bf0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_message_reads_message_id"),
        "message_reads",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_reads_message_id"), table_name="message_reads"
    )
    # ### end Alembic commands ###
