[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:fastapi]
command=gunicorn -c gunicorn_conf.py main:app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
