"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing
import user_pb2 as _user_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class UserServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> UserServiceAsyncStub: ...
    GetUser: _grpc.UnaryUnaryMultiCallable[_user_pb2.GetUserRequest, _user_pb2.UserResponse]

@_typing.type_check_only
class UserServiceAsyncStub(UserServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetUser: _aio.UnaryUnaryMultiCallable[_user_pb2.GetUserRequest, _user_pb2.UserResponse]  # type: ignore[assignment]

class UserServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetUser(
        self,
        request: _user_pb2.GetUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_user_pb2.UserResponse, _abc.Awaitable[_user_pb2.UserResponse]]: ...

def add_UserServiceServicer_to_server(servicer: UserServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
