"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    TENANT_FIELD_NUMBER: _builtins.int
    user_id: _builtins.int
    tenant: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.int = ...,
        tenant: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tenant", b"tenant", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUserRequest: _TypeAlias = GetUserRequest  # noqa: Y015

@_typing.final
class UserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    FIRST_NAME_FIELD_NUMBER: _builtins.int
    LAST_NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    first_name: _builtins.str
    last_name: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        first_name: _builtins.str = ...,
        last_name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["first_name", b"first_name", "id", b"id", "last_name", b"last_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserResponse: _TypeAlias = UserResponse  # noqa: Y015
